apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort                # <- Alterado de ClusterIP para NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30672          # <- Porta que você acessa do Windows para AMQP
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672          # <- Porta que você acessa do Windows para a UI
