apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
